ebs-driver:
  privileged: true
  net: host
  image: llparse/storage-ebs:dev
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: environment
  environment:
    AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
    AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
  volumes:
  - /run:/run
  - /dev:/host/dev
  - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
