version: '2'

services:
  db:
    image: llparse/asp-net-blog-db:latest
    labels:
      io.rancher.scheduler.affinity:host_label_soft: blogengine=db
    environment:
      sa_password: '$SA_PASSWORD'
    network_mode: transparent
  web:
    image: llparse/asp-net-blog-web:latest
    labels:
      io.rancher.scheduler.affinity:host_label_soft: blogengine=web
    environment:
      sa_password: '$SA_PASSWORD'
    network_mode: transparent
    depends_on:
    - db
  lb:
    image: llparse/lb-service-haproxy:dev
    command: lb-controller.sh --controller rancher --provider haproxy --metadata-address rancher-metadata:41
    ports:
    - 80:80/tcp
    network_mode: nat
    labels:
      io.rancher.container.dns: 'true'
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
