.catalog:
  name: Etcd
  version: v3.0.17
  minimum_rancher_version: v1.6.8-rc1
  questions:
  - variable: CONSTRAINT_TYPE
    label: Plane Isolation
    description: Isolate the data, orchestration and compute planes via host labels. Set to required when running in production.
    required: true
    default: none
    type: enum
    options:
    - none
    - required
  - variable: ETCD_HEARTBEAT_INTERVAL
    label: Etcd Heartbeat Interval
    description: Time (in milliseconds) of a heartbeat interval.
    required: true
    default: 500
    type: int
  - variable: ETCD_ELECTION_TIMEOUT
    label: Etcd Election Timeout
    description: Time (in milliseconds) for an election to timeout.
    required: true
    default: 5000
    type: int
  - variable: BACKUP_ENABLE
    label: Enable Backups
    description: "Periodically backup state to an NFS volume. You must install rancher-nfs before proceeding."
    required: true
    default: false
    type: boolean
  - variable: BACKUP_NAME
    label: Backup Volume Name
    description: Name of the external rancher-nfs volume to write snapshots to. This volume must be created beforehand!
    required: true
    default: etcd-backup
    type: string
  - variable: BACKUP_CREATION
    label: Backup Creation Period
    description: Create a backup after this amount of time passes. Must conform to duration format
    required: true
    default: 15m0s
    type: string
  - variable: BACKUP_RETENTION
    label: Backup Retention Period
    description: Expire a backup after this amount of time passes. Must conform to duration format
    required: true
    default: 24h
    type: string
  - variable: BACKUP_RESTORE
    label: Restore Backup
    description: Name of the external rancher-nfs volume to restore a cluster from.
    required: false
    type: string
etcd:
  health_check:
    port: 42
    request_line: GET /ping HTTP/1.0
    interval: 5000
    response_timeout: 3000
    unhealthy_threshold: 3
    healthy_threshold: 2
    initializing_timeout: 120000
    reinitializing_timeout: 120000
    recreate_on_quorum_strategy_config:
      quorum: 2
    strategy: recreateOnQuorum
  scale_policy:
    increment: 1
    max: 3
    min: 1
member:
  health_check:
    port: 2378
    request_line: GET /health HTTP/1.0
    interval: 5000
    response_timeout: 3000
    unhealthy_threshold: 3
    healthy_threshold: 2
    initializing_timeout: 120000
    reinitializing_timeout: 120000
    recreate_on_quorum_strategy_config:
      quorum: 2
    strategy: recreateOnQuorum
