name: SwarmKit Operator
version: 0.0.1
category: Framework
description: SwarmKit Operator for Linux and Windows.
projectURL: https://github.com/rancher/swarmkit-catalog
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,windows'
