name: Swarm
description: Default Swarm template
stacks:
  - name: swarm
    templateId: 'library:infra*swarm'
  - name: dns
    templateId: 'library:infra*dns'
  - name: metadata
    templateId: 'library:infra*metadata'
  - name: ipsec
    templateId: 'library:infra*ipsec'
  - name: network-manager
    templateId: 'library:infra*network-manager'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
