version: '2'

services:
    etcd-4:
        image: rancher/etcd:v2.3.7-11
        labels:
            io.rancher.scheduler.affinity:host_label_soft: etcd=true
            io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
        environment:
            RANCHER_DEBUG: 'true'
            EMBEDDED_BACKUPS: 'true'
            BACKUP_PERIOD: 1s
            BACKUP_RETENTION: 1m
        volumes:
        - etcd:/pdata
        - etcd_backup:/data-backup

volumes:
    etcd:
        driver: local
    etcd_backup:
        driver: rancher-ebs
        driver_opts:
            # GiB (4 GiB minimum for io1)
            size: 4
            # Provisioned IOPS SSD
            volumeType: io1
            # Range is 100 to 20000, maximum ratio of 30 per GiB
            iops: 120